// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace SuperKicks.Data.Models;

public partial class ApplicationUser:IdentityUser
{
    public int AppUserId { get; set; }

    public int CreatedBy { get; set; }

    public DateTimeOffset CraetedDateTime { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTimeOffset? UpdatedDateTime { get; set; }
}